schema_version: 3
initial:
  - CREATE TABLE IF NOT EXISTS LoanAccountTransaction (
    transaction_id           VARCHAR(256)       NOT NULL PRIMARY KEY,
    customer_profile_id      VARCHAR(256)       NOT NULL,
    end_customer_profile_id  VARCHAR(256)       NULL,
    loan_account_id          VARCHAR(256)       NOT NULL,
    amount                   DECIMAL(20, 10)    NOT NULL,
    txn_code                 VARCHAR(256)       NOT NULL,
    txn_type                 VARCHAR(256)       NOT NULL,
    sub_txn_type             VARCHAR(256)       NOT NULL,
    funding_account_id       VARCHAR(256)       NOT NULL,
    transceiver              JSON               NOT NULL,
    purpose                  VARCHAR(256)       NOT NULL,
    internal_details         JSON               DEFAULT (JSON_OBJECT()),
    currency                 VARCHAR(256)       NOT NULL,
    txn_count                SMALLINT UNSIGNED  NOT NULL DEFAULT 0,
    txn_status               VARCHAR(256)       NOT NULL,
    created_by               VARCHAR(256)       NOT NULL,
    accessed_by              JSON               DEFAULT (JSON_OBJECT()),
    notification_recipients  JSON               DEFAULT (JSON_OBJECT()),
    metadata                 JSON               NULL,
    location_details         JSON               DEFAULT (JSON_OBJECT()),
    deleted                  BOOLEAN            NOT NULL DEFAULT FALSE,
    run_ts                   TIMESTAMP(6)       NOT NULL,
    complete_ts              TIMESTAMP(6)       NULL,
    booking_ts               TIMESTAMP(6)       NOT NULL,
    value_ts                 TIMESTAMP(6)       NULL,
    create_ts                TIMESTAMP(6)       DEFAULT CURRENT_TIMESTAMP(6),
    update_ts                TIMESTAMP(6)       DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX account_id_index (loan_account_id),
    INDEX end_customer_profile_id_index (end_customer_profile_id)
    );

  - CREATE TABLE IF NOT EXISTS LoanAccountTransactionIdempotency (
    customer_profile_id VARCHAR(256)  NOT NULL,
    idempotency_key     VARCHAR(256)  NOT NULL,
    request_origin      VARCHAR(100)  NOT NULL,
    transaction_id      VARCHAR(256)  NOT NULL,
    deleted             BOOLEAN       NOT NULL DEFAULT FALSE,
    create_ts           TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
    update_ts           TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (customer_profile_id, idempotency_key, request_origin)
    );
